### ISSUE TITLE
Rebus bugs

### ISSUE THREAD

**Issue by frozenpandaman** [crosswordnexus/html5-crossword-solver#104]
Heyo @boisvert42, thought this would be helpful & be good to have written somewhere. Here are the issues I've identified with support for rebuses so far:
   - Puzzle will be marked as solved if all squares except rebuses are correct, and rebus squares will be changed to show answers
   - "Check" function will not mark a square incorrect if its answer is a rebus
   - ~~Non-blank squares which contain a rebus as the solution (whether filled in as such or not) will not change to the solved color upon revealing the puzzle solution~~

**Comment by crosswordnexus** [comment]
I consider those first two features and not bugs. I think the last one could stand to change, though, if I'm understanding what the issue is.

**Comment by frozenpandaman** [comment]
@crosswordnexus Thanks for the info! Why are those features? If you "check" a crossword, there's no way to see if the rebus you've inputted is correct or not. So that's not properly checking that square.

In addition, if someone doesn't fill in a rebus or two, but they get the rest of the squares, the puzzle will auto-solve and fill those squares in for them – this seems like behavior that could potentially spoil answers for solvers? Isn't that what the "reveal" feature is for?

I'm happy to provide more info about #3 if/when needed!

**Comment by crosswordnexus** [comment]
If a cell is a Schrodinger square where (say) either M or E is acceptable, we don't want the solver to have to guess which one is desired. If a cell is a question mark we want to let the solver type a Q if they want. See the [comments to this post](https://rexwordpuzzle.blogspot.com/2022/08/leafy-shelter-from-sun-wed-8-3-22.html) for people befuddled by what to put in a particular rebus square. This is what we're trying to avoid.

**Comment by frozenpandaman** [comment]
@crosswordnexus I see! I got around it in my fork by just removing the `// if we have a rebus or non-alpha solution, accept anything` block/logic, because I do want support for this type of stuff.

>If a cell is a Schrodinger square where (say) either M or E is acceptable, we don't want the solver to have to guess which one is desired.

I [added support](https://github.com/frozenpandaman/puz/blob/5a2c27f748513e324deaa9a3b2996ec28d411d5c/js/crosswords.js#L342-L349) for this explicitly, in case you're interested:
```
if (entry && (solution.constructor === Array)) {
	for (var i = 0; i < solution.length; i++) {
		if (entry == solution[i]) { // if any of the answers are entered, it's correct
			return true;
		}
	}
}
```

>If a cell is a question mark we want to let the solver type a Q if they want.

When are cells question marks? Just curious – I don't think I've seen a puzzle like this before.

>See the [comments to this post](https://rexwordpuzzle.blogspot.com/2022/08/leafy-shelter-from-sun-wed-8-3-22.html) for people befuddled by what to put in a particular rebus square.

Hahaha, I got confused by that puzzle too, no indication that's what was what to put there… (but IMO that's the puzzle's fault, in that case)
