### ISSUE TITLE
Preserve user solution when completing puzzle without a solution

### ISSUE THREAD

**Issue by jbierema** [crosswordnexus/html5-crossword-solver#106]
When a JPZ file without a solution is used and the user completes the puzzle, the user's answers are immediately replaced with *s, which is a little disconcerting and doesn't give users a chance to review and enjoy the puzzle, look at what the answers were to clues that they didn't need to figure out, etc.

I'm guessing this issue may have been introduced by #95.

Other than that, I'm pretty happy with the service you offer and hope to make good use of it in the future. Thanks!

**Comment by jbierema** [comment]
The biggest implementation question I have is what should be done if the solution to some cells is included in the file but not the solution to all cells. I don't have a use case for this, so I don't know whether it makes a difference. Maybe the cells that do have solutions should be updated and the rest left as-is? That seems the most straightforward and seems like a reasonable guess at what might be desired in that case, but I wanted to ask in case anyone has helpful insight.

**Comment by crosswordnexus** [comment]
I think the reason we introduced the "*" was for the case where some cells had a solution and others did not. This might re-introduce that bug but I think it's worth it.

**Comment by crosswordnexus** [comment]
Looking closer it seems you've accounted for that case. Thanks for filing the issue and the PR!
