### ISSUE TITLE
Handle "hint" cells

### ISSUE THREAD

**Issue by boisvert42** [crosswordnexus/html5-crossword-solver#37]
`<cell x="5" y="10" solution="C" hint="true" number="9"></cell>`

This results in a cell with an uneditable value filled in.  At the very least we should display those letters but make them editable.  Ideally we make them uneditable as well.

**Comment by crosswordnexus** [comment]
This is resolved as of https://github.com/crosswordnexus/html5-crossword-solver/commit/9c57d83a47b9e9984cfaa940fb677bbc81e86158
